github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Angus]
description: [Angus - Activation]

links:
  source: https://github.com/eclipse-ee4j/angus-activation
  javadocs: api/
  download: https://repo1.maven.org/maven2/org/eclipse/angus/angus-activation/
  mailinglist: https://accounts.eclipse.org/mailing-list/angus-dev
  spec: https://jakarta.ee/specifications/activation
  contrib: CONTRIBUTING
  tckresults: TCK-Results
